### ISSUE TITLE
What is the reason for computing bounding box for data producer?

### ISSUE THREAD

**Issue by LebronX** [eth-sri/lcifr#2]
Hi,

I don't understand why you compute a bounding box for the data producer. In the paper you said because "the stochastic nature of training", but in some iteration of training, it is possible that the set of output "breaks" this over-approximation, no?

Thanks

**Comment by anianruoss** [comment]
Hi @LebronX,

Thank you for your interest in our work!

During training, we try to enforce equation 3 of our paper, namely that all similar points should get mapped at most delta apart in latent space. However, due to the stochastic nature of training, this may or may not hold after training (or during any iteration of training, for that matter). Thus, once training has been completed, we use MILP to compute the smallest l-infinity bounding box that **provably** contains all similar points in latent space.

Cheers,

Anian

**Comment by LebronX** [comment]
Hi,

Thanks for the prompt reply!

I see. Can I understand this is because in some sense DL2 is doing "best-effort" training?

Thanks

**Comment by anianruoss** [comment]
Yes, DL2 empirically checks for constraint violations and adjusts the loss accordingly. However, since DL2 may not find all violations, we need to compute a provable over-approximation with MILP.

**Comment by LebronX** [comment]
I see. Thanks for the answer!
